#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register Domain
      shell: 'cat /var/plexguide/server.domain'
      register: domain
      ignore_errors: True

    - name: Register IP
      shell: 'cat /var/plexguide/server.ip'
      register: ipaddress
      ignore_errors: True

    - name: Register Ports
      shell: 'cat /var/plexguide/server.ports'
      register: ports
      ignore_errors: True

    - name: Register HD Path
      shell: 'cat /var/plexguide/server.hd.path'
      register: path
      ignore_errors: True

    - name: Register HD Path
      shell: 'cat /var/plexguide/server.hd.path'
      register: path
      ignore_errors: True

    - name: Register Auth Path
      shell: 'cat /var/plexguide/server.ht'
      register: auth
      ignore_errors: True

    - name: Logging Ansible Role Information
      shell: "echo 'INFO - Ansible Role Folders Started' > /var/plexguide/logs/pg.log && bash /opt/plexguide/menu/log/log.sh"

    ############ GCrypt
    - name: GCrypt Check
      stat:
        path: '{{path.stdout}}/gcrypt'
      register: gcrypt

    - name: Create GCrypt Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '{{path.stdout}}/gcrypt/tv'
        - '{{path.stdout}}/gcrypt/movies'
        - '{{path.stdout}}/gcrypt/music'
        - '{{path.stdout}}/gcrypt/ebooks'
        - '{{path.stdout}}/gcrypt/abooks'
      when: gcrypt.stat.exists == False
      ignore_errors: yes
    ############ TCrypt
    - name: TCrypt Check
      stat:
        path: '{{path.stdout}}/tcrypt'
      register: tcrypt

    - name: Create TCrypt Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '{{path.stdout}}/tcrypt/tv'
        - '{{path.stdout}}/tcrypt/movies'
        - '{{path.stdout}}/tcrypt/music'
        - '{{path.stdout}}/tcrypt/ebooks'
        - '{{path.stdout}}/tcrypt/abooks'
      when: tcrypt.stat.exists == False
      ignore_errors: yes

    ############ Personal Containers Folder
    - name: MyContainers Check
      stat:
        path: /opt/mycontainers
      register: mycontainers

    - name: Create MyContainers Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - /opt/mycontainers
      when: mycontainers.stat.exists == False
      ignore_errors: yes

    ############ PGUnion
    - name: Union Check
      stat:
        path: '{{path.stdout}}/unionfs'
      register: pgunion

    - name: Create Union Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '{{path.stdout}}/unionfs'
      when: pgunion.stat.exists == False
      ignore_errors: yes

    ############ TMP
    - name: TMP Check
      stat:
        path: '{{path.stdout}}/tmp'
      register: tmp

    - name: Create Temp Folder
      file: 'path={{item}} state=directory'
      with_items:
        - '{{path.stdout}}/tmp'
      when: tmp.stat.exists == False
      ignore_errors: yes

    ############ GDrive
    - name: GDrive Check
      stat:
        path: '{{path.stdout}}/gdrive'
      register: gdrive

    - name: Create GDrive Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '{{path.stdout}}/gdrive'
        - '{{path.stdout}}/gdrive/tv'
        - '{{path.stdout}}/gdrive/movies'
        - '{{path.stdout}}/gdrive/music'
        - '{{path.stdout}}/gdrive/ebooks'
        - '{{path.stdout}}/gdrive/abooks'
      when: gdrive.stat.exists == False
      ignore_errors: yes
    ############ TCrypt
    - name: Create TCrypt Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '{{path.stdout}}/tcrypt'
        - '{{path.stdout}}/tcrypt/tv'
        - '{{path.stdout}}/tcrypt/movies'
        - '{{path.stdout}}/tcrypt/music'
        - '{{path.stdout}}/tcrypt/ebooks'
        - '{{path.stdout}}/tcrypt/abooks'
      when: gdrive.stat.exists == False
      ignore_errors: yes

    ############ TDrive
    - name: TDrive Check
      stat:
        path: '{{path.stdout}}/tdrive'
      register: tdrive

    - name: Create TDrive Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '{{path.stdout}}/tdrive'
        - '{{path.stdout}}/tdrive/tv'
        - '{{path.stdout}}/tdrive/movies'
        - '{{path.stdout}}/tdrive/music'
        - '{{path.stdout}}/tdrive/ebooks'
        - '{{path.stdout}}/tdrive/abooks'
      when: tdrive.stat.exists == False
      ignore_errors: yes

    ############ Encrypt
    - name: Encrypt Check
      stat:
        path: '{{path.stdout}}/encrypt'
      register: encrypt

    - name: Create Encrypt Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '{{path.stdout}}/encrypt/tv'
        - '{{path.stdout}}/encrypt/movies'
        - '{{path.stdout}}/encrypt/music'
        - '{{path.stdout}}/encrypt/ebooks'
        - '{{path.stdout}}/encrypt/abooks'
      when: encrypt.stat.exists == False
      ignore_errors: yes

    - name: Create Basic Directories
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true'
      with_items:
        - '/opt/appdata/plexguide'
        - '/opt/appdata/plexguide/emergency'
        - '/opt/communityapps'
        - '/opt/coreapps'
        - '/var/plexguide'
        - '{{path.stdout}}/move'
        - '/var/plexguide/logs'
        - '/opt/appdata/plexguide/keys/unprocessed'
        - '/opt/appdata/plexguide/keys/processed'
        - '/opt/appdata/plexguide/keys/badjson'
        - '{{path.stdout}}/pgops'
        - '{{path.stdout}}/downloads'
        - '{{path.stdout}}/nzb'
        - '{{path.stdout}}/torrent'
        - '{{path.stdout}}/torrent/watch'
        - '{{path.stdout}}/move'
        - '/opt/var'
      ignore_errors: yes
