---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if Image Variable Exists
      stat:
        path: '/opt/communityapps'
      register: pathcheck

    - name: 'Transfer Image Variable'
      shell: 'rm -rf /opt/communityapps'
      when: pathcheck.stat.exists

    - name: Cloning Community Apps
      git:
        repo: 'https://github.com/PGBlitz/Apps-Community'
        dest: /opt/communityapps
        version: 'v8.6'
        force: yes
