#########################################################################
# Title:         Cloudbox: Plex Dupefinder Role                         #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set plex.user fact | username
  shell: 'cat /var/plex_dupe/plex.user'
  register: plexuser

- name: Set plex.user fact | passwort
  shell: 'cat /var/plex_dupe/plex.pw'
  register: plexpass

- name: Set plex.user fact | token
  shell: 'cat /var/plexguide/plex.token'
  register: plex_auth_token

- name: Set plex_dupe in automode 
  shell: 'cat /var/plex_dupe/plex.authdel'
  register: authdel

- name: Display Plex Auth Token
  debug:
    msg: "Plex Auth Token: {{ plex_auth_token.stdout }}"

- name: Create plex_dupefinder directories
  file: "path={{ item }} state=directory mode=0775 owner=1000 group=1000 recurse=yes"
  with_items:
    - /opt/plex_dupefinder

- name: Clone plex_dupefinder
  git:
    repo: https://github.com/l3uddz/plex_dupefinder.git
    dest: /opt/plex_dupefinder
    clone: yes
    version: HEAD
    force: yes
  become: yes
  become_user: "1000"

- name: Install pip requirements
  pip:
    requirements: /opt/plex_dupefinder/requirements.txt
    executable: pip3

- name: Check config exists
  stat:
    path: "/opt/plex_dupefinder/config.json"
  register: plex_dupefinder_config

- name: Import default config
  template:
    src: config.json.j2
    dest: /opt/plex_dupefinder/config.json
    owner: "1000"
    group: "1000"
    mode: 0775
    force: no
  when: not plex_dupefinder_config.stat.exists

- name: Set plexdupes.py as executable
  file:
    path: /opt/plex_dupefinder/plex_dupefinder.py
    owner: "1000"
    group: "1000"
    mode: a+x

- name: "Create /usr/local/bin symlink"
  file:
    src: "/opt/plex_dupefinder/plex_dupefinder.py"
    dest: "/usr/local/bin/plex_dupefinder"
    state: link
