---
- name : Update APT to latest packages 
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400
    force_apt_get: yes
  register: apt_result

- name: Upgrade Distrubution to the latest stable version
  apt:
    upgrade: full
    state: present
    force_apt_get: yes
  register: apt_result
 
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    allow_unauthenticated: yes
    force_apt_get: yes
    force: yes
    install_recommends: yes
  vars:
    packages:
    - ctop
    - dnsutils
    - software-properties-common
    - sysstat
    - nmon
    - cowsay 
    - fortune
    - figlet
    - lolcat

- name: Replace false to true in systat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED=true

- name: Ensure systat is ENABLED=true
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED=true

- name: Remove useless packages from the cache
  apt:
   autoclean: yes
   autoremove: yes
   force_apt_get: yes

- name: Fix filled /boot
  #shell: apt-get remove `dpkg --list 'linux-image*' | grep ^ii | awk '{print $2}'\ | grep -v \`uname -r\``
  shell:  dpkg -l linux-{image,headers}-"[0-9]*" | awk '/^ii/{ print $2}' | grep -v -e `uname -r | cut -f1,2 -d"-"` | grep -e '[0-9]' | xargs sudo apt-get -y purge

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=600 force_apt_get=yes

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"

- name: Purge residual kernel packages
  shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"
