---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=600

- name: Upgrade APT to the latest packages
  apt: upgrade=dist
  register: apt_result

- name: Install a list of packages
  apt:
    name:  "{{ packages }}"
    state: present
    update_cache:  yes
  vars:
    packages:
    - ctop
    - dnsutils
    - software-properties-common
    - sysstat 
    - nmon

- name: Replace false to true in systat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED=false'
    line: ENABLED=true

#- name: Ensure systat is ENABLED=true
#  lineinfile:
#    path: /etc/default/sysstat
#    regexp: '^ENABLED='
#    line: ENABLED=true

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"

- name: Purge residual kernel packages
  shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"
