---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=600
  register: apt_result

- name: Upgrade APT to the latest packages
  apt: upgrade=full
  register: apt_result

- name: Upgrade Distrubution to the latest stable version
  apt: upgrade=dist state=present only_upgrade=yes

- name: Install a list of packages
  apt:
    name:  "{{ packages }}"
    state: latest
    update_cache: yes
    allow_unauthenticated: yes
  vars:
    packages:
    - ctop
    - dnsutils
    - software-properties-common
    - sysstat
    - nmon

- name: Replace false to true in systat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED=true

- name: Ensure systat is ENABLED=true
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: ENABLED=true

- name: Remove useless packages from the cache
  apt:
   autoclean: yes

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"

- name: Purge residual kernel packages
  shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
  register: apt_result
  changed_when: "'packages will be REMOVED' in apt_result.stdout"
