---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if Image Variable Exists
      stat:
        path: '/opt/mycontainers'
      register: pathcheck

    - name: 'Transfer Image Variable'
      shell: 'rm -rf /opt/mycontainers'
      when: pathcheck.stat.exists
  
    - name: Register User for Personal Repo
      shell: 'cat /var/plexguide/boxpersonal.user'
      register: boxuser

    - name: Register Personal Repo
      shell: 'cat /var/plexguide/boxpersonal.repo'
      register: boxrepo

    - name: Register Personal Branch
      shell: 'cat /var/plexguide/boxpersonal.branch'
      register: boxbranch

    - name: 'Cloning {{boxuser.stdout}} Apps'
      git:
        repo: 'https://github.com/{{boxuser.stdout}}/{{boxrepo.stdout}}'
        dest: '/opt/mycontainers'
        clone: yes
        version: '{{boxbranch.stdout}}'
        force: yes
