#########################################################################
# Title:         Cloudbox: Traktarr Role                                #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check if pgtrakt_service exists
  stat:
    path: "/etc/systemd/system/pgtrakt.service"
  register: pgtrakt_service

- name: Stop existing pgtrakt_service
  systemd: state=stopped name=pgtrakt
  when: pgtrakt_service.stat.exists

- name: Remove | pgtrakt
  file: 'path={{item}} state=absent mode=0775 owner=1000 group=1000'
  with_items:
    - '/opt/appdata/pgtrakt/'
    - '/etc/systemd/system/pgtrakt.service'

- name: Check if traktarr service exists
  stat:
    path: "/etc/systemd/system/traktarr.service"
  register: traktarr_service

- name: Stop existing traktarr service
  systemd: state=stopped name=traktarr
  when: traktarr_service.stat.exists

- name: Create traktarr directories
  file: "path={{ item }} state=directory mode=0775 owner=1000 group=1000 recurse=yes"
  with_items:
    - /opt/appdata/traktarr

# - name: Clone traktarr v1.2.4
  # git:
    # repo: https://github.com/l3uddz/traktarr.git
    # dest: /opt/appdata/traktarr
    # version: release-1.2.4
    # force: yes
  # become: yes

- name: Check WebTools
  stat:
    path: '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle'
  register: trakarr

- name: Create Basic Directories
  file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
  with_items:
    - '/opt/appdata/traktarr'
  when:
    - trakarr.stat.exists == False

- name: Clone traktarr v1.2.4
  unarchive:
    src: https://github.com/l3uddz/traktarr/archive/1.2.4.zip
    dest: /opt/appdata/traktarr
    keep_newer: no
    owner: '1000'
    group: '1000'
    mode: 0775
    copy: no
  when:
    - traktarr.stat.exists == False

- name: Install pip requirements
  pip:
    requirements: /opt/appdata/traktarr/requirements.txt
    executable: pip3

- name: Check if traktarr config exists
  stat:
    path: "/opt/appdata/traktarr/config.json"
  register: traktarr_config

- name: Server ID
  shell: 'cat /var/plexguide/pg.serverid'
  register: serverid

- name: Token Recall
  shell: 'cat /var/plexguide/plex.token'
  register: plextoken

- name: Recall User
  shell: 'cat /var/plexguide/plex.user'
  register: user

- name: Register IP
  shell: 'cat /var/plexguide/server.ip'
  register: ipaddress

- name: Sonarr API
  shell: 'cat /var/plexguide/pgtrak.sapi'
  register: sapi
  ignore_errors: True

- name: Radarr API
  shell: 'cat /var/plexguide/pgtrak.rapi'
  register: rapi
  ignore_errors: True

- name: Sonarr Profile
  shell: 'cat /var/plexguide/pgtrak.sprofile'
  register: sprofile
  ignore_errors: True

- name: Radarr Profile
  shell: 'cat /var/plexguide/pgtrak.rprofile'
  register: rprofile
  ignore_errors: True

- name: Trakt.tv Client
  shell: 'cat /var/plexguide/pgtrak.client'
  register: client
  ignore_errors: True

- name: Trakt.tv Secret
  shell: 'cat /var/plexguide/pgtrak.secret'
  register: secret
  ignore_errors: True

- name: Radarr Path
  shell: 'cat /var/plexguide/pgtrak.rpath'
  register: rpath
  ignore_errors: True

- name: Sonarr Path
  shell: 'cat /var/plexguide/pgtrak.spath'
  register: spath
  ignore_errors: True

- name: Max allowed Year
  shell: 'cat /var/plexguide/pgtrakyear.max'
  register: year
  ignore_errors: True

- name: "Check if sonarr exists"
  stat:
    path: "/opt/appdata/sonarr/config.xml"
  register: sonarr_config
  when: not traktarr_config.stat.exists

- name: "When sonarr exists, add api key to traktar config"
  block:

  - name: Pull sonarr api key
    xml:
      path: "/opt/appdata/sonarr/config.xml"
      xpath: /Config/ApiKey
      content: text
    register: xmlresp

  - name: Set sonarr api Key
    set_fact:
      sonarr_api_key: "{{ xmlresp.matches[0].ApiKey }}"

  when: (not traktarr_config.stat.exists) and (sonarr_config.stat.exists)

- name: "Check if radarr exists"
  stat:
    path: "/opt/appdata/radarr/config.xml"
  register: radarr_config
  when: not traktarr_config.stat.exists

- name: "When radarr exists, add api key to traktar config"
  block:

  - name: Pull radarr api key
    xml:
      path: "/opt/appdata/radarr/config.xml"
      xpath: /Config/ApiKey
      content: text
    register: xmlresp

  - name: Set radarr api Key
    set_fact:
      radarr_api_key: "{{ xmlresp.matches[0].ApiKey }}"

  when: (not traktarr_config.stat.exists) and (radarr_config.stat.exists)

- name: Import default config
  template:
    src: /opt/plexguide/menu/roles/traktarr/templates/config.json.j2
    dest: /opt/appdata/traktarr/config.json
    owner: '1000'
    group: '1000'
    mode: 0775
    force: yes

- name: Set traktarr.py as executable
  file:
    path: /opt/appdata/traktarr/traktarr.py
    owner: '1000'
    group: '1000'
    mode: a+x

- name: Set directory permissions
  file: "path=/opt/appdata/traktarr state=directory owner=1000 group=1000 recurse=yes"

- name: "Create /usr/local/bin symlink"
  file:
    src: "/opt/appdata/traktarr/traktarr.py"
    dest: "/usr/local/bin/traktarr"
    state: link

- name: Import traktarr service
  template:
    src: /opt/plexguide/menu/roles/traktarr/templates/traktarr.service.j2
    dest: /etc/systemd/system/traktarr.service
    force: yes
  when: not traktarr_service.stat.exists

- name: Load traktarr service
  systemd:
    name: traktarr
    state: "{{ traktarr_config.stat.exists | ternary('started','stopped') }}"
    enabled: "{{ traktarr_config.stat.exists | ternary('yes','no') }}"
    daemon_reload: yes