#!/bin/bash
#
# Title:      Traktarr auto deploy
# Mod from MrDoobPG for PTS
# GNU:        General Public License v3.0
# Origin:     https://github.com/l3uddz/plex_patrol
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

   - name: Daily automatic add preconf lists for filling
     cron:
       special_time: 'daily'
       job: 'bash /opt/plexguide/menu/traktarr/traktarr-list/traktarr.sh >/dev/null 2>&1'
       state: present

