#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register Project
      shell: 'cat /var/plexguide/pg.number'
      register: serverid

    - name: Installing Version master
      git:
        repo: 'https://github.com/MrDoobPG/PGBlitz.com'
        dest: '/opt/plexguide'
        version: dev
        force: yes

    - name: 'Stops First Time Run'
      shell: 'touch /var/plexguide/ask.yes'
      register: program