##########################################################################
# Title:         Cloudbox: Plex | Extra Tasks                            #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: "DB Cache Size Settings"
  import_tasks: "subtasks/settings/db_cache_size.yml"
  tags: plex_db_cache_size

- name: "Forced Automatic Quality Settings"
  import_tasks: "subtasks/settings/forced_quality.yml"
  tags: plex_forced_quality
