#########################################################################
# Title:         Cloudbox: Kernel Role                                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Hetzner Tasks"
  import_tasks: "subtasks/hetzner.yml"
  tags: kernel-hetzner

- name: "Cron Tasks"
  include_tasks: "subtasks/cron.yml"

- name: "Mainline Kernel Script Tasks"
  include_tasks: "subtasks/script.yml"

- name: "Update Tasks"
  include_tasks: "subtasks/update.yml"

- name: "Header Tasks"
  include_tasks: "subtasks/headers.yml"

- name: "Checks Tasks"
  include_tasks: "subtasks/checks.yml"
