#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register Project
      shell: 'cat /var/plexguide/pg.number'
      register: serverid

    - name: 'Installing Version {{serverid.stdout}}'
      git:
        repo: 'https://github.com/PTS-Team/PTS-Team'
        dest: /opt/plexguide
        clone: yes
        version: '{{serverid.stdout}}'
        force: yes
        update: yes
      become: yes
      when: not serverid.stdout == "EDGE"
      ignore_errors: yes

    - stat:
        path: /opt/plexguide
      register: p
    - debug:
        msg: "Path exists and is a directory"
      when: p.stat.isdir is defined and p.stat.isdir

    - name: 'Stops First Time Run'
      shell: 'touch /var/plexguide/ask.yes'
      register: program
