---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Cloning PTS Install files'
      git:
        repo: 'https://github.com/PTS-Team/Install'
        dest: '/opt/pgstage'
        version: 'master'
        force: yes
