---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Cloning PGBlitz'
      git:
        repo: 'https://github.com/MrDoobPG/Install'
        dest: '/opt/pgstage'
        version: 'master'
        force: yes
