---
- name: Install Journald Fix
  template:
    src: journald.conf.sample
    dest: /etc/systemd/journald.conf
    force: yes

- name: systemd reloading
  systemd:
    daemon_reload: yes

#- name: Restarting Journald.conf
#  shell: sudo systemctl restart systemd-journald

- name: restart journald
  systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-journald
